LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := 7z 
LOCAL_MODULE := 7z
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := 7za 
LOCAL_MODULE := 7za
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := 7zr 
LOCAL_MODULE := 7zr
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := 7z.so
LOCAL_MODULE := 7z.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := Codecs/Rar.so
LOCAL_MODULE := Rar.so
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH = $(PRODUCT_OUT)/system/bin/Codecs/
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := unrar
LOCAL_MODULE := unrar
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
